let name=("Daniella");
console.log(name);
let age=(20);
console.log(age);
let y= 2 + 2;
console.log(y);
let z=8-4;
console.log(z);
let a=9 / 3;
console.log(a);
let b=4*5;
console.log(b);
let q=15%4;
console.log(q);
let gari=true;
console,log(gari);
let t=3;
console.log(typeof(t));
let i= ("Daniella");
console.log(typeof(i)); 